In [92]:
import firebase_admin
from firebase_admin import credentials, firestore

if not firebase_admin._apps:
    cred = credentials.Certificate("smart-agro-ai-fd974-firebase-adminsdk-fbsvc-aa086e000d.json")
    firebase_admin.initialize_app(cred)

db = firestore.client()

In [93]:
import pandas as pd
import numpy as np
from datetime import datetime

In [94]:
crop_df = pd.read_csv("crop_recommendation.csv")
soil_df = pd.read_csv("soil_nutrients.csv")

crop_df.head()

,rainfall_mm,moisture,temperature,nitrogen,phosphorus,potassium,crop
0,600,30,28,400,200,150,Wheat
1,800,50,32,450,220,180,Rice
2,400,25,30,350,180,120,Millet
3,700,45,29,420,210,160,Corn
4,900,60,31,500,250,200,Sugarcane

In [95]:
city = "Pune"
year = 2026
season = "Monsoon"
soil_type = "Black"

In [96]:
# Placeholder (later ESP32 se ayega)

moisture = 35
temperature = 29

In [97]:
soil_data = soil_df[soil_df["soil_type"] == soil_type]

nitrogen = soil_data["nitrogen"].values[0]
phosphorus = soil_data["phosphorus"].values[0]
potassium = soil_data["potassium"].values[0]

print(nitrogen, phosphorus, potassium)

480 230 190

In [98]:
input_df = pd.DataFrame({
    "city":[city],
    "year":[year],
    "season":[season],
    "moisture":[moisture],
    "temperature":[temperature],
    "nitrogen":[nitrogen],
    "phosphorus":[phosphorus],
    "potassium":[potassium]
})

input_df

   city  year   season  moisture  temperature  nitrogen  phosphorus  potassium
0  Pune  2026  Monsoon        35           29       480         230        190

In [99]:
data = {
    "city": city,
    "year": year,
    "season": season,
    "soil_type": soil_type,
    "moisture": float(moisture),
    "temperature": float(temperature),
    "nitrogen": float(nitrogen),
    "phosphorus": float(phosphorus),
    "potassium": float(potassium),
    "timestamp": datetime.now()
}

doc_ref = db.collection("farm_inputs").document()

doc_ref.set(data)

doc_id = doc_ref.id

print("Data pushed")
print("Doc ID:", doc_id)

Data pushed
Doc ID: lj8Rmp5I4vbUqhBMmNm2

In [100]:
rainfall = predict_rainfall(city, year, season)

print("Predicted Rainfall:", rainfall)

db.collection("farm_inputs").document(doc_id).update({
    "rainfall": float(rainfall)
})

print("Rainfall pushed successfully")

NameError: name 'predict_rainfall' is not defined

In [ ]:
filtered = crop_df[
    (crop_df["nitrogen"] <= nitrogen + 50) &
    (crop_df["phosphorus"] <= phosphorus + 50) &
    (crop_df["potassium"] <= potassium + 50)
]

recommended_crop = filtered.iloc[0]["crop"]

print("Recommended Crop:", recommended_crop)

In [ ]:
doc = db.collection("farm_inputs").document(doc_id)

doc.update({
    "recommended_crop": recommended_crop
})

print("Crop Updated")